theme: jekyll-theme-cayman
title: Bruno Silveira
description: I enjoy making new stuff and learning new things.
social:
  linkedin: https://www.linkedin.com/in/bruno-silveira-48478a90/
  github: http://github.com/brunossilveira
  instagram: http://instagram.com/brunossilveiraa
  blog: /blog
  email: djbrunosilveira@gmail.com
  twitter: https://twitter.com/brunossilveira