theme: jekyll-theme-cayman
author: Bruno Silveira
title: Bruno Silveira
url: https://brunossilveira.com
description: I enjoy making new stuff and learning new things.
mailchimp-list: https://brunossilveira.us14.list-manage.com/subscribe/post
social:
  linkedin: https://www.linkedin.com/in/bruno-silveira-48478a90/
  github: http://github.com/brunossilveira
  instagram: http://instagram.com/brunossilveiraa
  blog: /blog
  email: djbrunosilveira@gmail.com
  twitter: https://twitter.com/brunossilveira
plugins:
  - jekyll-feed
