theme: jekyll-theme-cayman
title: Bruno Silveira
description: Bruno Silveira
social:
  linkedin: https://www.linkedin.com/in/bruno-silveira-48478a90/
  github: http://github.com/brunossilveira
  instagram: http://instagram.com/brunossilveiraa
  blog: http://brunossilveira.github.io
  email: djbrunosilveira@gmail.com
  twitter: https://twitter.com/brunossilveira